In [1]:
import pandas as pd

# HW 4
In this homework you'll do some data manipulation on a real life dataset. Stats about the 2018-19 Brooklyn Nets.

Credit: https://www.basketball-reference.com/ for the dataset.

In [2]:
#Exercise 1
#read in bball_full.csv (from the data folder) making player names as index and store as a variable called data, only read in the first 16 rows
#Hint: to only read in the first 16 rows use one of the arguments in the read_csv function: https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html
data = pd.read_csv('data/bball_full.csv',index_col='Name',nrows=16)

### Note: The ability to only load in a select number of rows is extremely important when you are deadling with big data and don't want to crash your computer.

In [3]:
#Exercise 2
#Tell me the average (mean) and standard deviation of the Age of starters on the nets
#Note: Consider starters players as players for which GS (games started) is greater than or equal to 50% of G (games played)
print(data.loc[data.GS>1/2*data.G].Age.mean())
print(data.loc[data.GS>1/2*data.G].Age.std())

24.5
4.27617987059879

In [4]:
#Exercise 3
#Calculate True Shooting Percentage (https://en.wikipedia.org/wiki/True_shooting_percentage) and add it to the dataset as a column called TSP
#Who has the highest TSP on the nets?
#To see the player with the higehest TSP you may want to use those location max methods we talked about in numpy
data['TSP'] = (data.PTS/(2*data.FGA + (0.44 * data.FTA)))*100
data.TSP.idxmax()

'Alan Williams'

In [5]:
#Exericse 4
#read in bball_missing.csv (from the data folder) making player names as index and store as a variable called data_missing
data_missing = pd.read_csv('data/bball_missing.csv',index_col='Name')

In [6]:
#Exercise 5
#Tell me how many values are missing per row? per column?
print(data_missing.isnull().sum())
data_missing.isnull().sum(1)

Age     2
G       3
GS      5
MP      3
FG      4
FGA     4
FG%     4
3P      1
3PA     1
3P%     4
2P      4
2PA     0
2P%     5
eFG%    4
FT      2
FTA     1
FT%     3
ORB     2
DRB     2
TRB     2
AST     3
STL     1
BLK     7
TOV     3
PF      2
PTS     8
dtype: int64

Name
Caris LeVert               5
Joe Harris                 5
D'Angelo Russell           4
Spencer Dinwiddie          3
Jarrett Allen              4
Allen Crabbe               6
DeMarre Carroll            5
Rondae Hollis-Jefferson    5
Jared Dudley               3
Rodions Kurucs             4
Ed Davis                   4
Treveon Graham             6
Shabazz Napier             5
Theo Pinson                4
Kenneth Faried             3
Alan Williams              6
Dzanan Musa                8
dtype: int64

In [7]:
#Exercise 6
#Drop columns with nans but DO NOT actually modify data_missing
data_missing.dropna(1)

                          2PA
Name
Caris LeVert             10.2
Joe Harris                4.6
D'Angelo Russell         10.0
Spencer Dinwiddie         6.8
Jarrett Allen             6.9
Allen Crabbe              2.9
DeMarre Carroll           3.6
Rondae Hollis-Jefferson   8.0
Jared Dudley              1.6
Rodions Kurucs            4.2
Ed Davis                  3.9
Treveon Graham            1.9
Shabazz Napier            3.8
Theo Pinson               1.3
Kenneth Faried            3.1
Alan Williams             4.0
Dzanan Musa               1.1

In [8]:
#Exercise 7
#Fill nans with column means
#Here, you should actually modify data_missing
data.fillna(data.mean())

,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,TSP
Name,,,,,,,,,,,,,,,,,,,,,
Caris LeVert,24,14,14,29.7,6.9,14.6,0.475,1.4,4.4,0.311,...,1.0,3.3,4.3,3.7,1.2,0.4,2.1,2.4,18.4,59.095581
Joe Harris,27,40,40,29.4,4.9,9.6,0.506,2.4,5.0,0.483,...,0.8,2.9,3.6,2.4,0.6,0.2,1.5,2.9,13.4,67.622124
D'Angelo Russell,22,43,43,29.3,7.2,16.8,0.429,2.4,6.7,0.356,...,0.5,3.3,3.8,6.3,1.1,0.3,2.9,1.7,18.3,53.142061
Spencer Dinwiddie,25,44,4,28.5,5.5,12.0,0.455,1.9,5.3,0.364,...,0.4,2.1,2.5,5.0,0.6,0.2,2.3,2.8,16.9,64.395671
Jarrett Allen,20,42,42,26.5,4.4,7.5,0.584,0.1,0.6,0.160,...,2.6,5.7,8.3,1.4,0.6,1.5,1.3,2.4,11.5,69.160452
Allen Crabbe,26,28,15,26.1,3.0,8.9,0.343,2.3,6.0,0.387,...,0.5,3.0,3.5,1.1,0.6,0.3,1.1,2.4,9.5,51.585578
DeMarre Carroll,32,32,0,24.0,3.3,8.2,0.397,1.6,4.6,0.356,...,0.9,3.9,4.8,1.1,0.3,0.1,1.1,1.6,10.6,59.523810
Rondae Hollis-Jefferson,24,34,19,24.0,3.6,8.9,0.405,0.2,1.0,0.242,...,1.4,4.4,5.8,1.9,0.8,0.5,1.2,2.0,9.9,50.957381
Jared Dudley,33,43,25,22.0,1.8,4.4,0.405,0.9,2.8,0.322,...,0.6,2.2,2.8,1.5,0.7,0.3,0.9,2.4,5.0,54.632867
Rodions Kurucs,20,27,15,20.0,3.3,6.9,0.481,0.9,2.7,0.347,...,0.9,2.7,3.6,0.7,0.5,0.3,1.1,2.1,9.0,62.051848
Ed Davis,29,43,1,18.3,2.4,3.9,0.619,0.0,0.0,0.000,...,3.0,5.6,8.6,0.7,0.6,0.4,0.8,2.9,5.9,68.318666
Treveon Graham,25,7,1,18.1,1.0,5.0,0.200,0.4,3.1,0.136,...,0.9,1.3,2.1,0.9,0.4,0.4,0.7,1.6,2.7,26.648243
Shabazz Napier,27,33,1,16.9,2.9,7.1,0.406,1.2,3.3,0.370,...,0.3,1.5,1.8,2.1,0.7,0.3,1.1,1.3,8.9,58.337703
Theo Pinson,23,7,0,10.3,1.0,2.9,0.350,0.1,1.6,0.091,...,0.1,1.3,1.4,1.7,0.1,0.0,0.6,0.7,2.7,44.525066
Kenneth Faried,29,12,0,9.8,2.1,3.5,0.595,0.1,0.4,0.200,...,1.3,2.4,3.7,0.2,0.2,0.3,0.5,0.7,5.1,67.353407
Alan Williams,26,1,0,9.0,3.0,4.0,0.750,0.0,0.0,0.275,...,2.0,6.0,8.0,2.0,0.0,0.0,1.0,0.0,8.0,81.967213